kind: Template
apiVersion: v1
metadata:
    name: new-app-template-node-frontend
labels:
  new-app-template: ${PARAM_APP_NAME}-template
objects:
###############################################
#             Image Stream                    
###############################################
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      template: ${PARAM_APP_NAME}-template
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
    annotations:
      description: Realiza un seguimiento de los cambios en la imagen de la aplicación
###############################################
#           Build Config S2I
###############################################
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
      build: ${PARAM_APP_NAME}
      template: ${PARAM_APP_NAME}-template
    name: ${PARAM_APP_NAME}-s2i
    annotations:
        description: Define cómo construir la aplicación
        template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    source:
      type: Binary
    strategy:
      type: "Source"
      sourceStrategy:
        env:
        - name: NODE_OPTIONS
          value: '--max_old_space_size=4096'
        from:
          kind: "ImageStreamTag"
          namespace: openshift
          name: "nodejs:${NODEJS_VERSION}"
        scripts: http://ribera.claro.amx:8081/artifactory/local-openshift-release/scripts/s2i/nodejs-devops
    type: "Source"
    output:
      to:
        kind: "ImageStreamTag"
        name: ${PARAM_APP_NAME}:latest
###############################################
#            Deployment Config
###############################################
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${PARAM_APP_NAME}
    labels:
      app: ${PARAM_APP_NAME}
      template: ${PARAM_APP_NAME}-template
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - ${PARAM_APP_NAME}
        from:
          kind: ImageStreamTag
          namespace: ${PARAM_NAMESPACE}
          name: ${PARAM_APP_NAME}:${PARAM_DC_TAG}
    replicas: 2
    test: false
    template:
      metadata:
        labels:
          name: ${PARAM_APP_NAME}
          deploymentconfig: ${PARAM_APP_NAME}
      spec:
        containers:
        - name: ${PARAM_APP_NAME}
          env:
            - name: TZ
              value: ${TZ}
          image: ${REGISTRY_URL}/${PARAM_NAMESPACE}/${PARAM_APP_NAME}:${PARAM_DC_TAG}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30     
###############################################
#             Service
###############################################
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
      template: ${PARAM_APP_NAME}-template
    name: ${PARAM_APP_NAME}
    annotations:
      description: Expone y equilibra la carga de los módulos de aplicación
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
###############################################
#               Route
###############################################
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
      template: ${PARAM_APP_NAME}-template
    name: ${PARAM_APP_NAME}
  spec:
    host:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${PARAM_APP_NAME}
    weight: 100
    wildcardPolicy: None 
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    labels:
      template: ${PARAM_APP_NAME}-template
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-manage
    annotations:
      description: Publica Ruta para acceso externo al servicio para su monitoreo
  spec:
    path: /manage
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${PARAM_APP_NAME}  
parameters:
- name: PARAM_APP_NAME
  displayname: Application Name
  required: true
  description: Nombre de la aplicación
- name: PARAM_NAMESPACE
  displayname: Project Name (Namespace)
  required: true
  description: Nombre del proyecto (Namespace)
- name: PARAM_DC_TAG
  displayname: Tag a la imagen a usar
  value: latest
  description: tag usado para identificar la imagen a usar, latest en desarrollo, stage en testing y prod en producción
- name: TZ
  displayname: Timezone
  description: Timezone a utilizar al momento del deploy  
- name: NODEJS_VERSION
  displayName: Version of NodeJS Image
  description: Version of NodeJS image to be used (6, 8, or latest).
  value: '10'
  required: true
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  required: true
  value: 1536Mi
- name: REGISTRY_URL
  displayname: Registry_URL
  required: true
  description: Docker IS Registry URL
